package suniukai.model;

public class Darbuotojas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String pavarde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String pareigos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String viesbutis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotojas.ID
     *
     * @return the value of darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotojas.ID
     *
     * @param id the value for darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotojas.Vardas
     *
     * @return the value of darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotojas.Vardas
     *
     * @param vardas the value for darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotojas.Pavarde
     *
     * @return the value of darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getPavarde() {
        return pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotojas.Pavarde
     *
     * @param pavarde the value for darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setPavarde(String pavarde) {
        this.pavarde = pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotojas.Pareigos
     *
     * @return the value of darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getPareigos() {
        return pareigos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotojas.Pareigos
     *
     * @param pareigos the value for darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setPareigos(String pareigos) {
        this.pareigos = pareigos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotojas.Viesbutis
     *
     * @return the value of darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getViesbutis() {
        return viesbutis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotojas.Viesbutis
     *
     * @param viesbutis the value for darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setViesbutis(String viesbutis) {
        this.viesbutis = viesbutis;
    }
}