package suniukai.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Darbuotojas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Pavarde
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String pavarde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Pareigos
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String pareigos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotojas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String viesbutis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotojas.ID
     *
     * @return the value of darbuotojas.ID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */

    private Viesbutis viesbutis1;

    private List<Suniukas> suniukai;


}