package suniukai.model;

public class DarbuotojuSuniukuSarasas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotoju_suniuku_sarasas.SuniukoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String suniukoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column darbuotoju_suniuku_sarasas.DarbuotojoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String darbuotojoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotoju_suniuku_sarasas.SuniukoID
     *
     * @return the value of darbuotoju_suniuku_sarasas.SuniukoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getSuniukoid() {
        return suniukoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotoju_suniuku_sarasas.SuniukoID
     *
     * @param suniukoid the value for darbuotoju_suniuku_sarasas.SuniukoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setSuniukoid(String suniukoid) {
        this.suniukoid = suniukoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column darbuotoju_suniuku_sarasas.DarbuotojoID
     *
     * @return the value of darbuotoju_suniuku_sarasas.DarbuotojoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getDarbuotojoid() {
        return darbuotojoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column darbuotoju_suniuku_sarasas.DarbuotojoID
     *
     * @param darbuotojoid the value for darbuotoju_suniuku_sarasas.DarbuotojoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setDarbuotojoid(String darbuotojoid) {
        this.darbuotojoid = darbuotojoid;
    }
}