package suniukai.model;

public class Suniukas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suniukas.GyvunoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String gyvunoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suniukas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suniukas.Veisle
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String veisle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suniukas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String viesbutis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suniukas.GyvunoID
     *
     * @return the value of suniukas.GyvunoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getGyvunoid() {
        return gyvunoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suniukas.GyvunoID
     *
     * @param gyvunoid the value for suniukas.GyvunoID
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setGyvunoid(String gyvunoid) {
        this.gyvunoid = gyvunoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suniukas.Vardas
     *
     * @return the value of suniukas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suniukas.Vardas
     *
     * @param vardas the value for suniukas.Vardas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suniukas.Veisle
     *
     * @return the value of suniukas.Veisle
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getVeisle() {
        return veisle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suniukas.Veisle
     *
     * @param veisle the value for suniukas.Veisle
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setVeisle(String veisle) {
        this.veisle = veisle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suniukas.Viesbutis
     *
     * @return the value of suniukas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getViesbutis() {
        return viesbutis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suniukas.Viesbutis
     *
     * @param viesbutis the value for suniukas.Viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setViesbutis(String viesbutis) {
        this.viesbutis = viesbutis;
    }
}