package suniukai.model;

public class Viesbutis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viesbutis.Kodas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String kodas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viesbutis.Pavadinimas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String pavadinimas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column viesbutis.Adresas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    private String adresas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viesbutis.Kodas
     *
     * @return the value of viesbutis.Kodas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getKodas() {
        return kodas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viesbutis.Kodas
     *
     * @param kodas the value for viesbutis.Kodas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setKodas(String kodas) {
        this.kodas = kodas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viesbutis.Pavadinimas
     *
     * @return the value of viesbutis.Pavadinimas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viesbutis.Pavadinimas
     *
     * @param pavadinimas the value for viesbutis.Pavadinimas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column viesbutis.Adresas
     *
     * @return the value of viesbutis.Adresas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public String getAdresas() {
        return adresas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column viesbutis.Adresas
     *
     * @param adresas the value for viesbutis.Adresas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    public void setAdresas(String adresas) {
        this.adresas = adresas;
    }
}