package mano.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Patiekalas;

public interface PatiekalasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    int insert(Patiekalas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    Patiekalas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    List<Patiekalas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    int updateByPrimaryKey(Patiekalas record);
}