package mano.mybatis.dao;

import java.util.List;
import mano.mybatis.model.Patiekalas;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PatiekalasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int insert(Patiekalas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    Patiekalas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    List<Patiekalas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int updateByPrimaryKey(Patiekalas record);
}