package mano.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Patiekalasuzsakymas;
import org.apache.ibatis.annotations.Param;

public interface PatiekalasuzsakymasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalasuzsakymas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    int deleteByPrimaryKey(@Param("uzsakymas") Long uzsakymas, @Param("patiekalas") Integer patiekalas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalasuzsakymas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    int insert(Patiekalasuzsakymas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalasuzsakymas
     *
     * @mbg.generated Thu Mar 23 15:43:47 EET 2017
     */
    List<Patiekalasuzsakymas> selectAll();
}