package mano.mybatis.dao;

import java.util.List;
import mano.mybatis.model.Patiekalasuzsakymas;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PatiekalasuzsakymasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalasuzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int deleteByPrimaryKey(@Param("uzsakymas") Long uzsakymas, @Param("patiekalas") Integer patiekalas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalasuzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int insert(Patiekalasuzsakymas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalasuzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    List<Patiekalasuzsakymas> selectAll();
}