package mano.mybatis.dao;

import java.util.List;
import mano.mybatis.model.Uzsakymas;
import org.mybatis.cdi.Mapper;

@Mapper
public interface UzsakymasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int insert(Uzsakymas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    Uzsakymas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    List<Uzsakymas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    int updateByPrimaryKey(Uzsakymas record);
}