package mybatis.dao;

import java.util.List;
import mybatis.model.Patiekalas;

public interface PatiekalasMapper {

    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    int insert(Patiekalas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    Patiekalas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    List<Patiekalas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patiekalas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    int updateByPrimaryKey(Patiekalas record);
}