package mybatis.dao;

import java.util.List;
import mybatis.model.Virejas;

public interface VirejasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virejas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virejas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    int insert(Virejas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virejas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    Virejas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virejas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    List<Virejas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virejas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    int updateByPrimaryKey(Virejas record);
}