package mano.mybatis.model;

public class Patiekalasuzsakymas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patiekalasuzsakymas.uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Long uzsakymas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patiekalasuzsakymas.patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Integer patiekalas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patiekalasuzsakymas.uzsakymas
     *
     * @return the value of patiekalasuzsakymas.uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Long getUzsakymas() {
        return uzsakymas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patiekalasuzsakymas.uzsakymas
     *
     * @param uzsakymas the value for patiekalasuzsakymas.uzsakymas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setUzsakymas(Long uzsakymas) {
        this.uzsakymas = uzsakymas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patiekalasuzsakymas.patiekalas
     *
     * @return the value of patiekalasuzsakymas.patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Integer getPatiekalas() {
        return patiekalas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patiekalasuzsakymas.patiekalas
     *
     * @param patiekalas the value for patiekalasuzsakymas.patiekalas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setPatiekalas(Integer patiekalas) {
        this.patiekalas = patiekalas;
    }
}