package mano.mybatis.model;

public class Uzsakymas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uzsakymas.id
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uzsakymas.nr
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Long nr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uzsakymas.optlock
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Integer optlock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uzsakymas.virejas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Integer virejas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uzsakymas.id
     *
     * @return the value of uzsakymas.id
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uzsakymas.id
     *
     * @param id the value for uzsakymas.id
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uzsakymas.nr
     *
     * @return the value of uzsakymas.nr
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Long getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uzsakymas.nr
     *
     * @param nr the value for uzsakymas.nr
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setNr(Long nr) {
        this.nr = nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uzsakymas.optlock
     *
     * @return the value of uzsakymas.optlock
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Integer getOptlock() {
        return optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uzsakymas.optlock
     *
     * @param optlock the value for uzsakymas.optlock
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uzsakymas.virejas
     *
     * @return the value of uzsakymas.virejas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Integer getVirejas() {
        return virejas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uzsakymas.virejas
     *
     * @param virejas the value for uzsakymas.virejas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setVirejas(Integer virejas) {
        this.virejas = virejas;
    }
}