package mano.mybatis.model;

public class Virejas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virejas.id
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virejas.nr
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private Integer nr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virejas.vardas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private String vardas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virejas.pavarde
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    private String pavarde;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virejas.id
     *
     * @return the value of virejas.id
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virejas.id
     *
     * @param id the value for virejas.id
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virejas.nr
     *
     * @return the value of virejas.nr
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public Integer getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virejas.nr
     *
     * @param nr the value for virejas.nr
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setNr(Integer nr) {
        this.nr = nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virejas.vardas
     *
     * @return the value of virejas.vardas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public String getVardas() {
        return vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virejas.vardas
     *
     * @param vardas the value for virejas.vardas
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setVardas(String vardas) {
        this.vardas = vardas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virejas.pavarde
     *
     * @return the value of virejas.pavarde
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public String getPavarde() {
        return pavarde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virejas.pavarde
     *
     * @param pavarde the value for virejas.pavarde
     *
     * @mbg.generated Sat Mar 25 19:58:01 EET 2017
     */
    public void setPavarde(String pavarde) {
        this.pavarde = pavarde;
    }
}