package suniukai.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import suniukai.model.DarbuotojuSuniukuSarasas;

@Mapper
public interface DarbuotojuSuniukuSarasasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table darbuotoju_suniuku_sarasas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int deleteByPrimaryKey(@Param("suniukoid") String suniukoid, @Param("darbuotojoid") String darbuotojoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table darbuotoju_suniuku_sarasas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int insert(DarbuotojuSuniukuSarasas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table darbuotoju_suniuku_sarasas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    List<DarbuotojuSuniukuSarasas> selectAll();
}