package suniukai.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import suniukai.model.Suniukas;

@Mapper
public interface SuniukasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suniukas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int deleteByPrimaryKey(String gyvunoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suniukas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int insert(Suniukas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suniukas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    Suniukas selectByPrimaryKey(String gyvunoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suniukas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    List<Suniukas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suniukas
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int updateByPrimaryKey(Suniukas record);
}