package suniukai.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import suniukai.model.Viesbutis;

@Mapper
public interface ViesbutisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int deleteByPrimaryKey(String kodas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int insert(Viesbutis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    Viesbutis selectByPrimaryKey(String kodas);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    List<Viesbutis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viesbutis
     *
     * @mbg.generated Thu Mar 30 12:28:53 EEST 2017
     */
    int updateByPrimaryKey(Viesbutis record);
}