package mybatis.model;

public class Patiekalas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patiekalas.id
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patiekalas.optlock
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    private Integer optlock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patiekalas.nr
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    private Integer nr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patiekalas.pavadinimas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    private String pavadinimas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patiekalas.id
     *
     * @return the value of patiekalas.id
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patiekalas.id
     *
     * @param id the value for patiekalas.id
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patiekalas.optlock
     *
     * @return the value of patiekalas.optlock
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public Integer getOptlock() {
        return optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patiekalas.optlock
     *
     * @param optlock the value for patiekalas.optlock
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patiekalas.nr
     *
     * @return the value of patiekalas.nr
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public Integer getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patiekalas.nr
     *
     * @param nr the value for patiekalas.nr
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public void setNr(Integer nr) {
        this.nr = nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patiekalas.pavadinimas
     *
     * @return the value of patiekalas.pavadinimas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patiekalas.pavadinimas
     *
     * @param pavadinimas the value for patiekalas.pavadinimas
     *
     * @mbg.generated Thu Mar 23 15:56:30 EET 2017
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }
}